# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"

formats:
  - pdf

sphinx:
  configuration: doc/conf.py
  builder: dirhtml

python:
  install:
    - requirements: doc/requirements.txt
    - requirements: requirements.txt
